Blockly.Msg.WEBDUINO_IMAGEML_CAMERA_SRC = "相機位置：";
Blockly.Msg.WEBDUINO_IMAGEML_CAMERA_LOCAL = "本機";
Blockly.Msg.WEBDUINO_IMAGEML_MODEL_NAME = "，載入模型：";
Blockly.Msg.WEBDUINO_IMAGEML_CLASSIFY = "對影像進行分類，當分類編號為";
Blockly.Msg.WEBDUINO_IMAGEML_CLASSIFY2 = "時";
Blockly.Msg.WEBDUINO_IMAGEML_RUN = "執行";
Blockly.Msg.WEBDUINO_IMAGEML_LEVEL = "分類編號";
Blockly.Msg.WEBDUINO_IMAGEML_CONFIDENCE = "分類信心度";
