Blockly.Msg.WEBDUINO_IMAGEML_CAMERA_SRC = "相机位置：";
Blockly.Msg.WEBDUINO_IMAGEML_CAMERA_LOCAL = "本机";
Blockly.Msg.WEBDUINO_IMAGEML_MODEL_NAME = "，加载模型：";
Blockly.Msg.WEBDUINO_IMAGEML_CLASSIFY = "对影像进行分类，当分类编号为";
Blockly.Msg.WEBDUINO_IMAGEML_CLASSIFY2 = "时";
Blockly.Msg.WEBDUINO_IMAGEML_RUN = "执行";
Blockly.Msg.WEBDUINO_IMAGEML_LEVEL = "分类编号";
Blockly.Msg.WEBDUINO_IMAGEML_CONFIDENCE = "分类信心度";
